-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-14 19:46:13 COT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Cliente 
    ( 
     id_cliente    NUMBER (50)  NOT NULL , 
     nom_cliente   VARCHAR2 (200)  NOT NULL , 
     email_cliente VARCHAR2 (200)  NOT NULL , 
     tel_cliente   VARCHAR2 (10)  NOT NULL , 
     direc_cliente VARCHAR2 (200)  NOT NULL 
    ) 
;

ALTER TABLE Cliente 
    ADD CONSTRAINT Cliente_PK PRIMARY KEY ( id_cliente ) ;

CREATE TABLE Envio 
    ( 
     id_envio                       NUMBER (50)  NOT NULL , 
     fechasalida_envio              DATE  NOT NULL , 
     fechaentrega_envio             DATE  NOT NULL , 
     Ruta_id_ruta                   NUMBER (50)  NOT NULL , 
     Estado_envio_id_estado         NUMBER (50)  NOT NULL , 
     Transportista_id_transportista NUMBER (50)  NOT NULL , 
     Pedido_id_pedido               NUMBER (50)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX Envio__IDXv1 ON Envio 
    ( 
     Pedido_id_pedido ASC 
    ) 
;

ALTER TABLE Envio 
    ADD CONSTRAINT Envio_PK PRIMARY KEY ( id_envio ) ;

CREATE TABLE Estado_envio 
    ( 
     id_estado  NUMBER (50)  NOT NULL , 
     nom_estado VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE Estado_envio 
    ADD CONSTRAINT Estado_pedido_PK PRIMARY KEY ( id_estado ) ;

CREATE TABLE Item_pedido 
    ( 
     id_itempedido        NUMBER (50)  NOT NULL , 
     cantidad_itempedido  NUMBER (50) DEFAULT 1  NOT NULL , 
     precio_itempedido    FLOAT DEFAULT 0  NOT NULL , 
     Pedido_id_pedido     NUMBER (50)  NOT NULL , 
     Producto_id_producto NUMBER (50)  NOT NULL 
    ) 
;

ALTER TABLE Item_pedido 
    ADD CONSTRAINT Item_pedido_PK PRIMARY KEY ( id_itempedido ) ;

CREATE TABLE Pedido 
    ( 
     id_pedido          NUMBER (50)  NOT NULL , 
     fecha_pedido       DATE  NOT NULL , 
     total_pedido       DATE DEFAULT '0'  NOT NULL , 
     Cliente_id_cliente NUMBER (50)  NOT NULL 
    ) 
;

ALTER TABLE Pedido 
    ADD CONSTRAINT Pedido_PK PRIMARY KEY ( id_pedido ) ;

CREATE TABLE Producto 
    ( 
     id_producto        NUMBER (50)  NOT NULL , 
     nom_producto       VARCHAR2 (200)  NOT NULL , 
     categoria_producto VARCHAR2 (50)  NOT NULL , 
     precio_producto    FLOAT DEFAULT 30  NOT NULL 
    ) 
;

ALTER TABLE Producto 
    ADD CONSTRAINT Producto_PK PRIMARY KEY ( id_producto ) ;

CREATE TABLE Ruta 
    ( 
     id_ruta      NUMBER (50)  NOT NULL , 
     origen_ruta  VARCHAR2 (200)  NOT NULL , 
     destino_ruta VARCHAR2 (200)  NOT NULL , 
     km_ruta      FLOAT DEFAULT 500  NOT NULL 
    ) 
;

ALTER TABLE Ruta 
    ADD CONSTRAINT Ruta_PK PRIMARY KEY ( id_ruta ) ;

CREATE TABLE Transportista 
    ( 
     id_transportista       NUMBER (50)  NOT NULL , 
     nom_transportista      VARCHAR2 (200)  NOT NULL , 
     empresa_transportista  VARCHAR2 (200)  NOT NULL , 
     tel_transportista      NUMBER (10)  NOT NULL , 
     vehiculo_transportista VARCHAR2 (200)  NOT NULL 
    ) 
;

ALTER TABLE Transportista 
    ADD CONSTRAINT Transportista_PK PRIMARY KEY ( id_transportista ) ;

ALTER TABLE Envio 
    ADD CONSTRAINT Envio_Estado_envio_FK FOREIGN KEY 
    ( 
     Estado_envio_id_estado
    ) 
    REFERENCES Estado_envio 
    ( 
     id_estado
    ) 
;

ALTER TABLE Envio 
    ADD CONSTRAINT Envio_Pedido_FK FOREIGN KEY 
    ( 
     Pedido_id_pedido
    ) 
    REFERENCES Pedido 
    ( 
     id_pedido
    ) 
;

ALTER TABLE Envio 
    ADD CONSTRAINT Envio_Ruta_FK FOREIGN KEY 
    ( 
     Ruta_id_ruta
    ) 
    REFERENCES Ruta 
    ( 
     id_ruta
    ) 
;

ALTER TABLE Envio 
    ADD CONSTRAINT Envio_Transportista_FK FOREIGN KEY 
    ( 
     Transportista_id_transportista
    ) 
    REFERENCES Transportista 
    ( 
     id_transportista
    ) 
;

ALTER TABLE Item_pedido 
    ADD CONSTRAINT Item_pedido_Pedido_FK FOREIGN KEY 
    ( 
     Pedido_id_pedido
    ) 
    REFERENCES Pedido 
    ( 
     id_pedido
    ) 
;

ALTER TABLE Item_pedido 
    ADD CONSTRAINT Item_pedido_Producto_FK FOREIGN KEY 
    ( 
     Producto_id_producto
    ) 
    REFERENCES Producto 
    ( 
     id_producto
    ) 
;

ALTER TABLE Pedido 
    ADD CONSTRAINT Pedido_Cliente_FK FOREIGN KEY 
    ( 
     Cliente_id_cliente
    ) 
    REFERENCES Cliente 
    ( 
     id_cliente
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
